// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqlullwsvwueoboyeemm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxbHVsbHdzdnd1ZW9ib3llZW1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4NzcyNzcsImV4cCI6MjA2MjQ1MzI3N30.aQxUaTcJuR-A_UNYNhTeUqyLac-zNuF_wqk0NRpi33U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);